### ISSUE TITLE
Team list page - A link is displayed when a column is showed on right 

### ISSUE THREAD

**Issue by Galixte** [board3/Board3-Portal#481]
Hi,

when i activate the display for the right column, and when i go on this page:
```
/memberlist.php?mode=team 
```
In below the table of team list is displayed a link to the search engine:
```
GO_TO_SEARCH_ADV
```

The source code indicates this:
```
<p class="jumpbox-return">
<a class="" href="./search.php" title="Advanced search" accesskey="r">GO_TO_SEARCH_ADV</a>
</p>
```

**Comment by Galixte** [comment]
In fact all pages whose the link begins by /memberlist.php have the same problem of display.

**Comment by marc1706** [comment]
What modules do you have enabled in the right column? I'm unable to reproduce this issue

**Comment by marc1706** [comment]
Ah, it seems like you moved the search module to the right.

**Comment by Galixte** [comment]
Yes !

**Comment by Galixte** [comment]
The next modules are on the right:

Menu
Board style
Search
Statistics
The team
Random member
Top Posters
 Newest members
 Latest Bots
