### ISSUE TITLE
In the side Team block do not sort the groups, as may be adjusted in the ACP (manage user and group-> group-> group legend).

### ISSUE THREAD

**Issue by franki63** [board3/Board3-Portal#510]
open ./ext/board3/portal/modules/leaders.php
find
         $groups = array();

add after
         $order_legend = ($config['legend_sort_groupname']) ? 'group_name' : 'group_legend';

find
            $sql = 'SELECT group_id, group_name, group_colour, group_type

Replace with
            $sql = 'SELECT group_id, group_name, group_colour, group_type, group_legend

find
               ORDER BY group_name ASC';

Replace with
               ORDER BY ' . $order_legend . ' ASC';

find
         else
         {
            $sql = 'SELECT g.group_id, g.group_name, g.group_colour, g.group_type

Replace with
         else
         {
            $sql = 'SELECT g.group_id, g.group_name, g.group_colour, g.group_type, g.group_legend

find
               ORDER BY g.group_name ASC';

Replace with
               ORDER BY g.' . $order_legend . ' ASC';

**Comment by marc1706** [comment]
Related to: https://github.com/board3/Board3-Portal/issues/504
