### ISSUE TITLE
Set the portal as home page on the domain root

### ISSUE THREAD

**Issue by dragosvr92** [board3/Board3-Portal#552]
I have my forum located inside a directory and i need to set the portal page as the domain root.
The portal page is often used as a home page, so we need to be able to do this. 

Discussion on phpbb: 
https://www.phpbb.com/community/viewtopic.php?f=456&t=2259081&start=240#p14013726

**Comment by marc1706** [comment]
Work in process on the wiki:
https://github.com/board3/Board3-Portal/wiki/%5BHow-To%5D-Use-portal-as-index-page-with-forum-in-subfolder

**Comment by dragosvr92** [comment]
Thank you very much Marc. Its working fine.
