### ISSUE TITLE
Donations Module (Option for default currency)

### ISSUE THREAD

**Issue by sgtevmckay** [board3/Board3-Portal#555]
Greetings test this Extension on Sandbox board.

After setting up Donations Module in ACP, I returned to portal to Find that the donation was in Euro.
Can an option in the ACP be added to define default Currency?
In my case US

Also....where is a good place to make suggestions for additional Modules???

**Comment by marc1706** [comment]
This is exactly the place for posting issues you find or suggesting new features/modules.

**Comment by sgtevmckay** [comment]
Thank you
