### ISSUE TITLE
“Color for sunday” should be “color of first day of the week”

### ISSUE THREAD

**Issue by Galixte** [board3/Board3-Portal#564]
Hi,

if I disable this option:
```
'PORTAL_SUNDAY_FIRST_EXP'			=> 'If disabled the calendar will show Mo. --> Su., else Su. --> Sa.',
```

Monday begins each of row in calendar, it’s OK, but the “Color for sunday” will not colored the Monday, it makes no sense.

I think “Color for sunday” option should be renamed as “Color of first day of the week”.

Could you fix it ?

EDIT: Or did you want to stand out on Sunday from any other day with this option?

**Comment by marc1706** [comment]
This is correct the way it is right now. The idea is to highlight the sunday no matter which day is the displayed as first day of the week.
