### ISSUE TITLE
Style Module Not changing Style, and logging user off

### ISSUE THREAD

**Issue by sgtevmckay** [board3/Board3-Portal#581]
Portal 3 Build: RC3 
Module: Board Styles
Issue: By Default I am using Style WoWDraenor. If I select "prosilver" from Portal screen, I am logged off of Portal/forum.\
Must log back in to portal/forum.
When I log back in WoWDraenor remains, and does not switch to prosilver style.
ACP settings are set to allow users to define default Style for them selves. WoWDraenor is set as default, and Override Users Style is set to "off"

May not do you a lot go good, but here is the link to my site. If you need sign in credentials, please advise, I will create a logon for you specifically.
http://gated.ddns.net/phpBB3/app.php/portal
Be gentle, link is to a small home server with limited bandwidth.

**Comment by marc1706** [comment]
Have you checked your cookie settings? Looking at the link the stylechanger module creates, it seems like the SID is correctly appended. Therefore I'm suspecting that your cookie settings might have an incorrect domain set.

**Comment by sgtevmckay** [comment]
Entirely Possible....This "Sandbox" forum is a copy of an active Forum, when I moved the DB and teh build, I may have missed something. I will double check all my settings now, and get back to you soon.

**Comment by sgtevmckay** [comment]
Ok.....
Reset Cookie settings, Cleared Cache of Board, cleared all cookies settings for account .....
Issue remains
As you have pointed out, this issue maybe on my end, as this is a reconstructed site for Extensions testing and style Build/modification. So I will continue working the problem

**Comment by sgtevmckay** [comment]
OK....I guess you can close this as an issue.
I just tried the extension at 2 other test sites and it works fine, so it must be something on my end.
I will figure out what is wrong with my build.

My apologies
Thanks for your time
