### ISSUE TITLE
Prepare package for 2.1.0 release

### ISSUE THREAD

**Issue by marc1706** [board3/Board3-Portal#616]
- [x] Update copyrights in portal files, footer
  - [x] Check in portal_body files
  - [x] Check date in composer.json
- [x] Update target version in composer.json
- [x] Add migration for 2.1.0
- [x] Build Board3 Portal 2.1.0
- [x] Check for unused files in package
- [x] Create tag for 2.1.0

- [x] Create announcement on board3.de
- [x] Update topic on phpbb.com
- [x] Update http://board3.de/updatecheck/board3_portal.json

**Comment by Galixte** [comment]
I’m happy to see that, thanks for all !
