### ISSUE TITLE
IIS forum image aren’t displayed in forum list module/block

### ISSUE THREAD

**Issue by Galixte** [board3/Board3-Portal#645]
Hi @marc1706,

on IIS server with 2.1.0-RC3 release the forum image aren’t displayed in forumlist module/block.

On index page the code is:
```
<img src="./imacatfor/bi.jpg" alt="Aucun message non lu">
```
For the image found at:
```
http://fsfrancesimulateur2.fr/forum/imacatfor/bi.jpg
```

On the portal page, the code is the same:
```
<img src="./imacatfor/bi.jpg" alt="Aucun message non lu">
```
However, on the portal page the image is searched at:
```
http://fsfrancesimulateur2.fr/forum/app.php/imacatfor/bi.jpg
```

**Comment by marc1706** [comment]
It seems like your IIS server is incorrectly configured. Make sure the URL rewrite module is enabled on your server. I've tested this with the current dev version of Board3 Portal and phpBB 3.1.6. The rewrite works without issues for me.

**Comment by Galixte** [comment]
Thanks.
