### ISSUE TITLE
IIS serveur URL rewritting don’t displayed the /portal page

### ISSUE THREAD

**Issue by Galixte** [board3/Board3-Portal#646]
Hi @marc1706,

on IIS serveur with 2.1.0-RC3 release the URL rewriting activated doesn’t show the portal on the /portal page.

http://fsfrancesimulateur2.fr/forum/app.php/portal works but not on the next page: http://fsfrancesimulateur2.fr/forum/portal

**Comment by marc1706** [comment]
See this comment: https://github.com/board3/Board3-Portal/issues/645#issuecomment-140370547

**Comment by Galixte** [comment]
Thanks.
