### ISSUE TITLE
Slight misalignment of forum content with portal on all pages

### ISSUE THREAD

**Issue by marc1706** [board3/Board3-Portal#656]
See related forum topic for images: http://board3.de/viewtopic.php?f=72&t=11042&view=unread#unread

**Comment by Galixte** [comment]
Hi @marc1706,

i encountered a similar issue, here: https://github.com/Tatiana5/profile_side_switcher/issues/9, which xas solved in two PR, here: https://github.com/Tatiana5/profile_side_switcher/pull/10 & https://github.com/Tatiana5/profile_side_switcher/pull/18.

**Comment by Galixte** [comment]
Maybe it’s the Arcade extension which should be fixed by non conventional coding.
