### ISSUE TITLE
Problems with board3 "forumlist" and we_universal 

### ISSUE THREAD

**Issue by Wignatz** [board3/Board3-Portal#657]
Hello all.

I have a problem with we_universal and board3. I've put all the files in the correct folder and it works fine, but...:

Look at the "forum list module" at my page http://forum.veggie4life.de/app.php/portal!
All the items like "statistic" and "last contribution" are moved and disordered.

Can you help me with my problem? 
Thanks a lot

**Comment by Galixte** [comment]
@marc1706 , Wignatz uses this PR for information.

**Comment by Wignatz** [comment]
Ive put all the files (board3/portal/styles/we_universal/theme) in the correct folder...Portal and Portal_responsive.css

**Comment by Galixte** [comment]
It’s fixed here: https://github.com/Galixte/Board3-Portal/commit/deaf32a35413ba54fa48d714b71ada971780c9ef & https://github.com/Galixte/Board3-Portal/commit/307712920e7261ba33b81d10203eab81ae4dc7b4.

**Comment by Galixte** [comment]
@Wignatz maybe you could close this issue, now.

**Comment by marc1706** [comment]
Closing this. See #654
