### ISSUE TITLE
Not showing for registered groups besides administrators

### ISSUE THREAD

**Issue by whi5p** [board3/Board3-Portal#664]
Admins can see the portal fine, but other groups, with a bit more limited permissions on the forum itself can't. What's surprising - when they log out and try as guests it works just fine, and guests are very limited in their permissions. I couldn't really find any options concerning permissions in the extension itself, not sure if there are any.

Seems that we're not the only ones with the problem too.
https://www.phpbb.com/customise/db/extension/board3_portal_ext/support/topic/152726

**Comment by Galixte** [comment]
Hi @whi5p,

https://www.phpbb.com/customise/db/extension/board3_portal_ext/support/topic/152726?p=461781#p461781.

**Comment by whi5p** [comment]
Thanks you very much, I didn't notice that option. Issue resolved. ;)
