### ISSUE TITLE
Forum icons and disabled mod_rewrite

### ISSUE THREAD

**Issue by bissim** [board3/Board3-Portal#665]
Hello @marc1706,
in some environment, the mod_rewrite option can't be enabled; in this case, if forum list is shown into the portal, forum icons throws errors because they cannot be found.
That's obvious, since they're not in domain/app.php/images/... .
Could you sort this issue out?

**Comment by marc1706** [comment]
I'm not sure what you mean by this exactly?
Your server does not support mod_rewrite.

Forumlist on portal: Icons correctly show.
Display of forums with portal on all pages: works fine.

**Comment by Mauron** [comment]
Forum icons do not show in Portal page if mod_rewrite is disabled.

**Comment by marc1706** [comment]
Just to confirm:
The forum icons in the forumlist module do not show if mod_rewrite is disabled and while using apache. The page is access via yourdomain.com/app.php/portal and the rewrite option is disabled in the ACP.
Correct?

**Comment by Mauron** [comment]
That's right.

**Comment by marc1706** [comment]
Can't reproduce that on the current development version.

**Comment by marc1706** [comment]
Closing as there hasn't been an update in a long time and issue could not be reproduced.
