### ISSUE TITLE
Portal incompatible with phpBB 3.2.0

### ISSUE THREAD

**Issue by marc1706** [board3/Board3-Portal#690]
The portal currently has a few major issues that also prevent tests from running without failures.

**Comment by Galixte** [comment]
Hi @marc1706,

did you see this thread: http://reyno41.bplaced.net/phpbb/viewtopic.php?style=1&f=19&t=194 ?

Regards.

**Comment by Galixte** [comment]
Hi @marc1706,

it seems that a new change appeared: http://reyno41.bplaced.net/phpbb/viewtopic.php?style=1&p=842#p842.

**Comment by Galixte** [comment]
Hi @marc1706,

an other : http://reyno41.bplaced.net/phpbb/viewtopic.php?style=1&f=19&t=239

**Comment by Galixte** [comment]
Hi @marc1706,

did you see the fixes integrated by @Sajaki on his fork: https://github.com/Sajaki/Board3-Portal/commits/develop32?

**Comment by marc1706** [comment]
Yes, saw those. I don't fully understand why nobody asked for access to this repo. The reason this was set up on the board3 account was to prevent having to fork in case this would move on to other authors.

I also noticed that most changes are flawed with respect to CI breakage and not complying with the coding guidelines (also see the related FA PR on this repository). I approve of people taking the time to improve Board3 Portal and making it work on 3.2 but the basic principles of good quality code and improving CI shouldn't be thrown overboard at the same time.

**Comment by Sajaki** [comment]
Those are some tall words Mark. I only did what lots of people were asking. Will not bother to continue working on Board3 then.

**Comment by marc1706** [comment]
I very much appreciate the work and time you put into this and I'm not disapproving of this in any way. I think you're misunderstanding what I was trying to say.

Overall I think it makes more sense to integrate the changes into the main repository as stated above. I can directly add you as a contributor which will allow you to push to this repository and merge/close pull requests if that sounds good to you.

The continuous integration (CI) has been broken for quite a while and I saw that the builds have been failing for you as well due. Reason for these failures are:
- Changes in phpBB that required changes. Something I have fixed for the current state of 2.1.x and master on this repository
- You seem to have added dependencies to the composer.json and composer.lock file that seem to be incompatible with PHP 5.4. I haven't looked into the exact issue but this needs to be resolved to allow travis to successfully run builds on PHP 5.4 again
- Changes in the FA PR have added code with spaces instead of tabs. This does not comply with the phpBB coding guidelines and will also cause CI builds to fail. Travis complained about this in the original PR: https://travis-ci.org/board3/Board3-Portal/jobs/238902447

I was merely trying to state that these should be fixed and as a matter of fact I was able to fix the travis builds for both branches on this repository. Having CI up and running as well as complying with the phpBB coding guidelines is very important to me and will both help with preventing future bugs and ensuring that the portal can potentially pass validation. The tabs vs. spaces issue is something that would have been picked up by validation on .com and, due to the extent, would have probably resulted in a denial.

P.S.: It's Marc with a c at the end ;)

**Comment by glebsts** [comment]
screw you both, men, make it official plsss

**Comment by HDValentin** [comment]
[board3_fix_for_login.zip](https://github.com/board3/Board3-Portal/files/3564856/board3_fix_for_login.zip)
Could someone with expertise please integrate this fix into this repo?

**Comment by glebsts** [comment]
@HDValentin  please elaborate on what exactly was fixed, any issue tracker link or smth.

**Comment by HDValentin** [comment]
The portal is not working with phpbb 3.2.X 
These fixes are fixing the problems.
I can't say what exactly was fixed. 
I can only say that the portal is working with these fixes. 
Without it won't.

**Comment by Galixte** [comment]
Currently updated for phpBB 3.3.x: https://reyno41.bplaced.net/phpbb/viewtopic.php?f=33&t=228

**Comment by HDValentin** [comment]
@Galixte I've just tested the files from the linked forum. When I upload them I get a white site, instead of the forum.

**Comment by Galixte** [comment]
> @Galixte I've just tested the files from the linked forum. When I upload them I get a white site, instead of the forum.

Maybe some files are corrupted on your FTP, upload these again.

**Comment by HDValentin** [comment]
@Galixte it was my fault. I updated the wrong way.
The Files are working correctly.

**Comment by marc1706** [comment]
Current master should also now work on 3.3.x
