### ISSUE TITLE
Bug format data

### ISSUE THREAD

**Issue by msaulohenrique** [board3/Board3-Portal#697]
Hello!
I made a change in the block of recent topics, but it has returned the error:
[phpBB Debug] PHP Warning: in file [ROOT]/ext/board3/portal/modules/recent.php on line 87: Missing argument 8 for board3/portal/modules/recent::__construct(), called in [ROOT]/cache/container_0374ec857381230fa83049643ce3cdee.php on line 827 and defined

My code: https://gist.github.com/msaulohenrique/a7f50b3c330d65a300937a1ec482ff1c

**Comment by marc1706** [comment]
Sounds like you didn't purge the cache afterwards and/or didn't update the config for recent topics module.
