### ISSUE TITLE
PHP Fatal error:  Call to undefined function Marc1706\TextShortener\striipos()

### ISSUE THREAD

**Issue by Galixte** [board3/Board3-Portal#702]
Hi @marc1706,

on phpBB 3.2.0, i have this error from Apache logs:

```[21-Jun-2017 06:51:20 Europe/Berlin] PHP Fatal error:  Call to undefined function Marc1706\TextShortener\striipos() in /forum/ext/board3/portal/vendor/marc1706/phpbb-text-shortener/src/TextIterator.php on line 120```

The displaying of the portal is currently like a blank page for admin/founder users while simple registered users & guests can view the portal.

Apache 2.2.31 / PHP 5.5.27 / MySQL 5.6.35.

Could you fix this, please ?

**Comment by marc1706** [comment]
Fixed in master with latest version of text shortener.
