### ISSUE TITLE
Content-Encoding-Error when edit block

### ISSUE THREAD

**Issue by HDValentin** [board3/Board3-Portal#703]
I have installed PHPBB 3.2.1
PHP Version 7.1.8
Board3 Portal Version 2.1.0

When I want to change a portal block in the phpbb backend I get a
Content-Encoding-Error in the Browser (Firefox).

Is there a newer Version of Board3Portal? 
The latest Reelease 2.1.0 is from 26 Oct 2015
Where can I find it?

**Comment by Galixte** [comment]
Hi,

i don’t have this behaviour. What is the type of change did you do? An update of the content from a block or…? Add more details from your issue, please.

**Comment by HDValentin** [comment]
I've updated from PHPBB 3.2.0 to PHPBB 3.2.1
I'm getting this message when I click on 
extensions > Portal > Portal modules > settings of a specific module
>> it is only one of the portal modules generating this error.

Another Browser gives the following message:
"Inhaltsdekodierung des Antworttextkörpers ist fehlgeschlagen.
https://domain.info/adm/index.php?i=-board3-portal-acp-portal_module&sid=d0b9e3b19bca9291b80e46e6123cfc9e&mode=config&module_id=25"

Is it save to install the latest snapshot in a productive system?

**Comment by HDValentin** [comment]
I just tried to create a new "own block".
When I click on edit settings of this new block I get the same error message.

**Comment by Galixte** [comment]
I think It’s not a problem from phpBB or this extension, you can try to re-upload your files from this extension on your FTP, to purge your board cache and delete your Firefox cookies and cache, then try again.

**Comment by HDValentin** [comment]
I don't think so. I am going to try these changes and report then the results here:
https://github.com/board3/Board3-Portal/pull/691/files

Found it here in German language:
https://www.board3.de/viewtopic.php?f=72&t=11267#p37073

These are also changes to have be done when the 2.1.0 should work on phpbb 3.2.x with php 7.0:
http://reyno41.bplaced.net/phpbb/viewtopic.php?f=19&t=194

**Comment by HDValentin** [comment]
Exactly this solved my problem!
https://www.board3.de/viewtopic.php?f=72&t=11267#p37075

It would be great for all the users of board3portal if there will be a new release that works with PHP7.1 and phpBB 3.2.1

**Comment by Galixte** [comment]
Thanks for report!

Hi @marc1706, could you take a look, please?
