### ISSUE TITLE
custom block

### ISSUE THREAD

**Issue by Prosk8er** [board3/Board3-Portal#711]
if you make a custom block in acp then go to edit it you get this
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 789: A non-numeric value encountered
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 790: A non-numeric value encountered
[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions_content.php on line 791: A non-numeric value encountered
php version 7.1
phpbb 3.2.5
portal version latest github version

block does work though and can be edited
error is only displayed in acp when editing the custom block

**Comment by Galixte** [comment]
Hi @Prosk8er,

did you compare with the @Sajaki version available here: https://github.com/Sajaki/Board3-Portal?

**Comment by MixingOnBeat** [comment]
Not only does it affect the **Custom Block**, but also the **Welcome Message** block as well.  It seems to trigger it if the block has a text box.

Could it be a PHP 7 issue?

**Comment by Galixte** [comment]
@Prosk8er @MixingOnBeat I found this, maybe: https://github.com/Sajaki/Board3-Portal/pull/3/files

**Comment by MixingOnBeat** [comment]
@Galixte -- thanks that code update fixed the issue on my portal.

**Comment by HDValentin** [comment]
Could we fix this issue here in the code?

**Comment by Galixte** [comment]
> Could we fix this issue here in the code?

You can submit un Pull Request.

**Comment by HDValentin** [comment]
I could copy and paste it.
but I am unsure if I do it the right way.

**Comment by marc1706** [comment]
Fixed in latest master.
